### ISSUE TITLE
dart not loading uppercase/lowercase issue?

### ISSUE THREAD

**Issue by themindfactory** [ssantoshp/The-Oracle#3]
Did pip install beibo and it seems to be unable to find dart library, looks like it loaded it, but it calls it DART not dart... all other libs show up in lowercase

**Comment by themindfactory** [comment]
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from beibo import oracle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Users\SW2021\anaconda3\envs\spyder\Lib\site-packages\beibo.py", line 6, in <module>
    from DARTS.utils.missing_values import fill_missing_values
ModuleNotFoundError: No module named 'DARTS.utils.missing_values'; 'DARTS.utils' is not a package
>>> import darts.util
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'darts'
>>> import darts
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'darts'
>>> import DARTS
>>> import DARTS.utils

**Comment by themindfactory** [comment]
I swapped to a linux env from windows 10 and was able to get it all loaded and compiled fine.... must be some windows thing.... so we are good, however I had issues with the code and needed to tweak some to make it work, will create a new 'Issue' for that....

**Comment by santoshlite** [comment]
Ok, this looks strange... Thanks anyway!
